<a href="https://colab.research.google.com/github/mariatomy9/Major-Project/blob/main/Copy_of_TEST_AND_train.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

!apt-get update && apt-get install -y libffi-dev libcairo2-dev


In [ ]:
!pip install eeglib

In [ ]:
!pip install reportlab


In [ ]:
!pip install -q pyngrok

!pip install -q streamlit

!pip install -q streamlit_ace

In [ ]:
!pip install PyPDF2

!pip install fpdf



In [ ]:
!pip install mne
!pip install pyEDFlib
!pip install EDFlib-Python
# !pip install fpdf
# !pip install reportlab


# ***LSTM*** **PREDICT**

In [ ]:
from __future__ import print_function
import pandas as pd
import eeglib
from eeglib.helpers import EDFHelper
import mne
from collections import Counter
import statistics
import streamlit as st
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score
import os
import time
import random
import glob
import librosa
import numpy as np
import librosa.display
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
import matplotlib.pyplot as plt
import numpy as np
from numpy import loadtxt
import seaborn as sn
import pandas as pd
import keras
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import GRU,LSTM
from keras.models import Sequential
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from tensorflow.keras.callbacks import  ModelCheckpoint
from tensorflow.keras.models import Model, load_model
from keras.layers.core import Dense, Activation
from keras.layers.core import Dropout
from keras.layers import BatchNormalization
from keras.layers import Dropout
from sklearn.metrics import classification_report


epilepsy_data = pd.read_csv('/content/original_epilepsy_types_new6.csv')
epilepsy_data =epilepsy_data.drop(['Unnamed: 0'],axis=1)
x=epilepsy_data[['PFD0', 'PFD1', 'PFD2', 'PFD3', 'PFD4', 'PFD5', 'PFD6', 'PFD7', 'PFD8',
       'PFD9', 'PFD10', 'PFD11', 'PFD12', 'PFD13', 'PFD14', 'PFD15', 'PFD16',
       'PFD17', 'PFD18', 'PFD19', 'PFD20', 'PFD21', 'PFD22', 'DTW',
       'hjorthActivity0', 'hjorthActivity1', 'hjorthActivity2',
       'hjorthActivity3', 'hjorthActivity4', 'hjorthActivity5',
       'hjorthActivity6', 'hjorthActivity7', 'hjorthActivity8',
       'hjorthActivity9', 'hjorthActivity10', 'hjorthActivity11',
       'hjorthActivity12', 'hjorthActivity13', 'hjorthActivity14',
       'hjorthActivity15', 'hjorthActivity16', 'hjorthActivity17',
       'hjorthActivity18', 'hjorthActivity19', 'hjorthActivity20',
       'hjorthActivity21', 'hjorthActivity22']]
# print("x",x)

y = epilepsy_data.loc[:,'Label'].values
# print("y",y)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x)
x = scaler.transform(x)
# print("x",x)
# print("X-train",x.shape)

from keras.utils import to_categorical
y = to_categorical(y)
# print("y",y)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)
# print("x_train",x_train)
# print("x_test",x_test)
# print("y_train",y_train)
# print("y_test",y_test)
# print("X-train",x_train.shape)

x_train1 = np.reshape(x_train, (x_train.shape[0],1,x.shape[1]))
x_test1 = np.reshape(x_test, (x_test.shape[0],1,x.shape[1]))
# print("x_train1",x_train1)
# print("x_test1",x_test1)


# dataframe2 = pd.read_csv('/content/CHANDRIKA_new.csv')
# dataframe1 = dataframe2.drop(dataframe2.columns[0],axis=1)
# dataframe = np.reshape(dataframe1.values, (dataframe1.shape[0],1,47))

# print("dataframe",dataframe)


# # Read CSV file

# # num_rows and num_cols are the dimensions of each 2D slice of the data
# # -1 in the reshape function means that the size of this dimension will be inferred from the input data

# # Print the shape of the original and reshaped data

# result = prediction(dataframe)
# print(result)


In [17]:
model = Sequential()
model.add(LSTM(64, input_shape=(1,47),activation="relu",return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(32,activation="sigmoid"))
model.add(Dropout(0.2))
# model.add(LSTM(100,activation="sigmoid",return_sequences=True))
# model.add(Dropout(0.2))
#model.add(LSTM(50))
#model.add(Dropout(0.2))
model.add(Dense(7, activation='sigmoid'))
# # from keras.optimizers import SGD
# # model.compile(loss = 'categorical_crossentropy', optimizer = "adam", metrics = ['accuracy'])
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x_train1, y_train, epochs = 10, validation_data= (x_test1, y_test))
# model.summary()

Epoch 1/10
709/709 [==============================] - 7s 6ms/step - loss: 0.9853 - accuracy: 0.6878 - val_loss: 0.4178 - val_accuracy: 0.8970
Epoch 2/10
709/709 [==============================] - 5s 7ms/step - loss: 0.3939 - accuracy: 0.8877 - val_loss: 0.2624 - val_accuracy: 0.9250
Epoch 3/10
709/709 [==============================] - 4s 5ms/step - loss: 0.2854 - accuracy: 0.9153 - val_loss: 0.2040 - val_accuracy: 0.9404
Epoch 4/10
709/709 [==============================] - 4s 6ms/step - loss: 0.2328 - accuracy: 0.9314 - val_loss: 0.1677 - val_accuracy: 0.9506
Epoch 5/10
709/709 [==============================] - 5s 7ms/step - loss: 0.1991 - accuracy: 0.9415 - val_loss: 0.1470 - val_accuracy: 0.9524
Epoch 6/10
709/709 [==============================] - 5s 6ms/step - loss: 0.1719 - accuracy: 0.9483 - val_loss: 0.1278 - val_accuracy: 0.9624
Epoch 7/10
709/709 [==============================] - 4s 5ms/step - loss: 0.1501 - accuracy: 0.9546 - val_loss: 0.1110 - val_accuracy: 0.9672
Epoch 

In [18]:
from sklearn.metrics import accuracy_score
pred = model.predict(x_test1)
predict_classes = np.argmax(pred,axis=1)
expected_classes = np.argmax(y_test,axis=1)
print(expected_classes.shape)
print(predict_classes.shape)
correct = accuracy_score(expected_classes,predict_classes)
print(f"Training Accuracy: {correct}")

178/178 [==============================] - 1s 2ms/step
(5669,)
(5669,)
Training Accuracy: 0.9726583171635209


In [ ]:
def prediction(dataframe):  
  
  prediction1 = model.predict(dataframe)
  predict_classes = np.argmax(prediction1,axis=1)
  print(prediction1)
  print(predict_classes)
  counts = np.bincount(predict_classes)
  prediction2 = np.argmax(counts)
    
      
  if (prediction2 == 0):
      pred = 'Dis1 Generalised Epilepsy'
  elif (prediction2 == 1):
      pred = 'Dis3 Generalised Epilepsy'
  elif (prediction2 == 2):
      pred = 'Delta Generalised Epilepsy'
  elif (prediction2 == 3):
      pred = 'Single burst Generalised Epilepsy'
  elif (prediction2 == 4):
      pred = 'Temporal Epilepsy'
  elif (prediction2 == 5):
      pred = 'Frontocentral Epilepsy'
  else:
      pred = 'Frontopolar Epilepsy'
  return pred

In [19]:
dataframe2 = pd.read_csv('/content/CHANDRIKA_new.csv')
dataframe1 = dataframe2.drop(dataframe2.columns[0],axis=1)
dataframe = np.reshape(dataframe1.values, (dataframe1.shape[0],1,47))

print("dataframe",dataframe)


# # Read CSV file

# # num_rows and num_cols are the dimensions of each 2D slice of the data
# # -1 in the reshape function means that the size of this dimension will be inferred from the input data

# # Print the shape of the original and reshaped data

result = prediction(dataframe)
print(result)


dataframe [[[1.02274558 1.02662849 1.02688558 ... 0.98588699 1.01967924 0.77284831]]

 [[1.02065391 1.02662849 1.02352619 ... 2.03149141 1.00757298 0.84439921]]

 [[1.01960254 1.02662849 1.02430478 ... 1.16483441 0.65793283 1.59396334]]

 ...

 [[1.02144001 1.02662849 1.02559794 ... 0.75523915 1.04273155 1.07722045]]

 [[1.02352619 1.02662849 1.02611366 ... 0.77393522 0.89890893 1.01221462]]

 [[1.00308268 1.00558023 1.0053038  ... 0.48255633 0.30559272 1.54709062]]]
48/48 [==============================] - 0s 2ms/step
[[0.2124261  0.08860274 0.459672   ... 0.998237   0.10849103 0.00591363]
 [0.24691088 0.06991768 0.6009037  ... 0.997812   0.154503   0.00435462]
 [0.24132738 0.06825758 0.4868826  ... 0.99794626 0.10216304 0.00646963]
 ...
 [0.26577327 0.05556071 0.5116344  ... 0.997683   0.09874768 0.00685465]
 [0.23495549 0.07208946 0.4789212  ... 0.9980133  0.10260433 0.00639835]
 [0.21983299 0.135737   0.60695225 ... 0.996208   0.04683216 0.00196475]]
[4 4 4 ... 4 4 4]
Temporal Epil

In [ ]:
from tensorflow.keras.models import load_model
import numpy as np
import pandas as pd
import numpy as np


def prediction(dataframe):  
  
  loaded_model = load_model('my_lstm_model.h5')
  predictions = loaded_model.predict(dataframe)
  predict_classes = np.argmax(predictions,axis=1)
  print(predictions)
  print(predict_classes)
  counts = np.bincount(predict_classes)
  prediction2 = np.argmax(counts)
  # prediction2 = statistics.mode(predict_classes)
    
      
  if (prediction2 == 0):
      pred = 'Dis1 Generalised Epilepsy'
  elif (prediction2 == 1):
      pred = 'Dis3 Generalised Epilepsy'
  elif (prediction2 == 2):
      pred = 'Delta Generalised Epilepsy'
  elif (prediction2 == 3):
      pred = 'Single burst Generalised Epilepsy'
  elif (prediction2 == 4):
      pred = 'Temporal Epilepsy'
  elif (prediction2 == 5):
      pred = 'Frontocentral Epilepsy'
  else:
      pred = 'Frontopolar Epilepsy'
  return pred

dataframe2 = pd.read_csv('/content/AYYAPPAN_new.csv')
dataframe1 = dataframe2.drop(dataframe2.columns[0],axis=1)
dataframe = np.reshape(dataframe1.values, (dataframe1.shape[0],1,47))

print("dataframe",dataframe)


# # Read CSV file

# # num_rows and num_cols are the dimensions of each 2D slice of the data
# # -1 in the reshape function means that the size of this dimension will be inferred from the input data

# # Print the shape of the original and reshaped data

result = prediction(dataframe)
print(result)


dataframe [[[1.02662849 1.02662849 1.02637118 ... 1.16685042 1.4595501  0.92741697]]

 [[1.02662849 1.02714245 1.02611366 ... 1.02931888 1.46465106 0.86628169]]

 [[1.02662849 1.02714245 1.02842353 ... 0.93500071 1.68428728 0.85668026]]

 ...

 [[1.02662849 1.02662849 1.02637118 ... 1.0702378  2.20867011 1.3509542 ]]

 [[1.02662849 1.02637118 1.02559794 ... 1.08560434 1.07983597 1.34438107]]

 [[1.02662849 1.02842353 1.02533975 ... 0.74838719 2.3479041  1.33830904]]]
48/48 [==============================] - 0s 2ms/step
[[0.7849979  0.05838296 0.9472467  ... 0.11790462 0.01594914 0.00542297]
 [0.78443325 0.06706448 0.9317989  ... 0.1590677  0.01376868 0.00521348]
 [0.73816526 0.05287977 0.93822175 ... 0.18133414 0.01628599 0.00653989]
 ...
 [0.7558785  0.0153192  0.96797    ... 0.26394394 0.02619442 0.00286607]
 [0.77080005 0.01147985 0.96299016 ... 0.3470748  0.02833138 0.00339243]
 [0.8392653  0.05712704 0.9179039  ... 0.18087131 0.01371456 0.005598  ]]
[2 2 2 ... 2 2 2]
Delta General

# **MODEL** **SAVE**

In [ ]:
epilepsy_data

PFD0      PFD1      PFD2      PFD3      PFD4      PFD5      PFD6  \
0      1.026628  1.026628  1.026114  1.026628  1.026628  1.024564  1.025340   
1      1.026628  1.026628  1.026628  1.026628  1.026886  1.026114  1.025081   
2      1.026628  1.026628  1.025598  1.026628  1.027142  1.026114  1.025081   
3      1.026628  1.026628  1.024823  1.026628  1.026886  1.025598  1.023006   
4      1.026628  1.026628  1.023526  1.026628  1.026114  1.026114  1.025598   
...         ...       ...       ...       ...       ...       ...       ...   
46720  1.023526  1.026628  1.026628  1.025598  1.027912  1.026628  1.018812   
46721  1.019603  1.026628  1.025856  1.024045  1.024305  1.020129  1.019339   
46722  1.021440  1.026628  1.025598  1.024045  1.023006  1.021963  1.018018   
46723  1.023526  1.026628  1.026114  1.025598  1.024305  1.020391  1.017754   
46724  1.003083  1.005580  1.005304  1.005580  1.005304  1.004750  1.003918   

           PFD7      PFD8      PFD9  ...  hjorthActivity14  hjorthActivity15  \
0      1.024045  1.026628  1.023526  ...          0.465618          0.427841   
1      1.024823  1.026628  1.024305  ...          0.310774          0.304385   
2      1.027142  1.026628  1.023266  ...          0.329698          0.342481   
3      1.025081  1.025856  1.021440  ...          3.803939          1.429145   
4      1.024564  1.027142  1.023526  ...          4.826091          1.286788   
...         ...       ...       ...  ...               ...               ...   
46720  1.024045  1.025598  1.026628  ...          1.238771          0.828179   
46721  1.024045  1.026628  1.026628  ...          1.036385          0.871316   
46722  1.026628  1.025340  1.026628  ...          1.002664          0.681747   
46723  1.026628  1.025340  1.026628  ...          1.010949          0.818405   
46724  1.005304  1.005580  1.005304  ...          0.244710          0.196636   

       hjorthActivity16  hjorthActivity17  hjorthActivity18  hjorthActivity19  \
0              1.078657          0.102130          0.267037          0.330682   
1              0.948840          0.092594          0.223569          0.242099   
2              1.094572          0.082353          0.207086          0.195659   
3              1.223469          0.141066          0.582976          0.190388   
4              1.074185          0.146749          1.779844          0.390236   
...                 ...               ...               ...               ...   
46720          0.775156          0.743153          1.181999          2.627862   
46721          1.378759          1.146180          1.926221          1.939588   
46722          0.862714          0.896996          1.166359          1.765986   
46723          0.745265          0.951690          3.911023          1.679892   
46724          0.019369          0.112196         47.153660          0.064425   

       hjorthActivity20  hjorthActivity21  hjorthActivity22  Label  
0              0.287038          0.236045          0.219049    0.0  
1              0.359904          0.224586          0.241306    0.0  
2              0.304122          0.247518          0.245281    0.0  
3              0.458770          0.199284          0.329741    0.0  
4              0.327588          0.293795          1.008775    0.0  
...                 ...               ...               ...    ...  
46720          0.679125          1.056220          1.085311    6.0  
46721          0.856601          3.065395          1.230423    6.0  
46722          0.755239          1.042732          1.077220    6.0  
46723          0.773935          0.898909          1.012215    6.0  
46724          0.482556          0.305593          1.547091    6.0  

[46725 rows x 48 columns]

In [54]:
from __future__ import print_function
import pandas as pd
import eeglib
from eeglib.helpers import EDFHelper
import mne
from collections import Counter
import statistics
import streamlit as st
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score
import os
import time
import random
import glob
import librosa
import numpy as np
import librosa.display
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
import matplotlib.pyplot as plt
import numpy as np
from numpy import loadtxt
import seaborn as sn
import pandas as pd
import keras
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import GRU,LSTM
from keras.models import Sequential
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from tensorflow.keras.callbacks import  ModelCheckpoint
from tensorflow.keras.models import Model, load_model
from keras.layers.core import Dense, Activation
from keras.layers.core import Dropout
from keras.layers import BatchNormalization
from keras.layers import Dropout
from sklearn.metrics import classification_report


epilepsy_data = pd.read_csv('/content/original_epilepsy_types_new6.csv')
epilepsy_data =epilepsy_data.drop(['Unnamed: 0'],axis=1)
x=epilepsy_data[['PFD0', 'PFD1', 'PFD2', 'PFD3', 'PFD4', 'PFD5', 'PFD6', 'PFD7', 'PFD8',
       'PFD9', 'PFD10', 'PFD11', 'PFD12', 'PFD13', 'PFD14', 'PFD15', 'PFD16',
       'PFD17', 'PFD18', 'PFD19', 'PFD20', 'PFD21', 'PFD22', 'DTW',
       'hjorthActivity0', 'hjorthActivity1', 'hjorthActivity2',
       'hjorthActivity3', 'hjorthActivity4', 'hjorthActivity5',
       'hjorthActivity6', 'hjorthActivity7', 'hjorthActivity8',
       'hjorthActivity9', 'hjorthActivity10', 'hjorthActivity11',
       'hjorthActivity12', 'hjorthActivity13', 'hjorthActivity14',
       'hjorthActivity15', 'hjorthActivity16', 'hjorthActivity17',
       'hjorthActivity18', 'hjorthActivity19', 'hjorthActivity20',
       'hjorthActivity21', 'hjorthActivity22']]
y = epilepsy_data.loc[:,'Label'].values
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x)
x = scaler.transform(x)
from keras.utils import to_categorical
y = to_categorical(y)
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)
x_train1 = np.reshape(x_train, (x_train.shape[0],1,x.shape[1]))
x_test1 = np.reshape(x_test, (x_test.shape[0],1,x.shape[1]))
model = Sequential()
model.add(LSTM(64, input_shape=(1,47),activation="sigmoid",return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(32,activation="sigmoid"))
model.add(Dropout(0.2))
#model.add(LSTM(100,return_sequences=True))
#model.add(Dropout(0.2))
#model.add(LSTM(50))
#model.add(Dropout(0.2))
model.add(Dense(7, activation='sigmoid'))
from keras.optimizers import SGD
model.compile(loss = 'categorical_crossentropy', optimizer = "adam", metrics = ['accuracy'])

model.fit(x_train1, y_train, epochs = 50, validation_data= (x_test1, y_test))
model.save('my_lstm_model.h5')

Epoch 1/50
709/709 [==============================] - 8s 6ms/step - loss: 1.4328 - accuracy: 0.4842 - val_loss: 0.9104 - val_accuracy: 0.7329
Epoch 2/50
709/709 [==============================] - 3s 5ms/step - loss: 0.7819 - accuracy: 0.7453 - val_loss: 0.5700 - val_accuracy: 0.8621
Epoch 3/50
709/709 [==============================] - 3s 5ms/step - loss: 0.5746 - accuracy: 0.8223 - val_loss: 0.4249 - val_accuracy: 0.8860
Epoch 4/50
709/709 [==============================] - 5s 7ms/step - loss: 0.4688 - accuracy: 0.8563 - val_loss: 0.3503 - val_accuracy: 0.8995
Epoch 5/50
709/709 [==============================] - 4s 5ms/step - loss: 0.4105 - accuracy: 0.8732 - val_loss: 0.3092 - val_accuracy: 0.9100
Epoch 6/50
709/709 [==============================] - 3s 5ms/step - loss: 0.3751 - accuracy: 0.8830 - val_loss: 0.2808 - val_accuracy: 0.9164
Epoch 7/50
709/709 [==============================] - 3s 5ms/step - loss: 0.3479 - accuracy: 0.8917 - val_loss: 0.2582 - val_accuracy: 0.9224
Epoch 

In [59]:
from tensorflow.keras.models import load_model
import numpy as np
import pandas as pd
import numpy as np


# Load the saved model
loaded_model = load_model('my_lstm_model.h5')
dataframe2 = pd.read_csv('/content/ABDULSALMAN_new.csv')
dataframe2 = dataframe2.drop(dataframe2.columns[0],axis=1)
# dataframe2 = dataframe2.drop(dataframe2.columns[-1],axis=1)
dataframe2.columns = ['PFD0', 'PFD1', 'PFD2', 'PFD3', 'PFD4', 'PFD5', 'PFD6', 'PFD7', 'PFD8',
                                 'PFD9', 'PFD10', 'PFD11', 'PFD12', 'PFD13', 'PFD14', 'PFD15', 'PFD16',
                                  'PFD17', 'PFD18', 'PFD19', 'PFD20', 'PFD21', 'PFD22', 'DTW','hjorthActivity0', 'hjorthActivity1', 'hjorthActivity2',
                                  'hjorthActivity3', 'hjorthActivity4', 'hjorthActivity5',
                                  'hjorthActivity6', 'hjorthActivity7', 'hjorthActivity8',
                                  'hjorthActivity9', 'hjorthActivity10', 'hjorthActivity11',
                                  'hjorthActivity12', 'hjorthActivity13', 'hjorthActivity14',
                                  'hjorthActivity15', 'hjorthActivity16', 'hjorthActivity17',
                                  'hjorthActivity18', 'hjorthActivity19', 'hjorthActivity20',
                                  'hjorthActivity21', 'hjorthActivity22']

from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler()
# scaler.fit(dataframe1)
dataframe2 = scaler.transform(dataframe2)

dataframe2 = np.array(dataframe2).reshape((dataframe2.shape[0],1,47))# Reshape the 2D array into a 3D array
# Make predictions using the loaded model
predictions = loaded_model.predict(dataframe2)
predict_classes = np.argmax(predictions,axis=1)
print("pred",prediction)
print("pred class",predict_classes)
prediction2 = statistics.mode(predict_classes)
print("pred2",prediction2)


48/48 [==============================] - 1s 3ms/step
pred <function prediction at 0x7fe5af1c63b0>
pred class [2 2 2 ... 2 2 2]
pred2 2


# IF COLUMNS OF CSV **NOT** ***IN*** ***ORDER***

In [41]:
dataframe5 = pd.read_csv('/content/CHANDRIKA_new.csv')
dataframe6 = dataframe5.drop(dataframe5.columns[0],axis=1)
dataframe6 = dataframe6.columns[['PFD0', 'PFD1', 'PFD2', 'PFD3', 'PFD4', 'PFD5', 'PFD6', 'PFD7', 'PFD8',
       'PFD9', 'PFD10', 'PFD11', 'PFD12', 'PFD13', 'PFD14', 'PFD15', 'PFD16',
       'PFD17', 'PFD18', 'PFD19', 'PFD20', 'PFD21', 'PFD22', 'DTW',
       'hjorthActivity0', 'hjorthActivity1', 'hjorthActivity2',
       'hjorthActivity3', 'hjorthActivity4', 'hjorthActivity5',
       'hjorthActivity6', 'hjorthActivity7', 'hjorthActivity8',
       'hjorthActivity9', 'hjorthActivity10', 'hjorthActivity11',
       'hjorthActivity12', 'hjorthActivity13', 'hjorthActivity14',
       'hjorthActivity15', 'hjorthActivity16', 'hjorthActivity17',
       'hjorthActivity18', 'hjorthActivity19', 'hjorthActivity20',
       'hjorthActivity21', 'hjorthActivity22']]
dataframe6.to_csv("/content/CHANDRIKA_new1.csv")
# dataframe2 = pd.read_csv('/content/patient_new.csv')
# dataframe1 = dataframe2.drop(dataframe2.columns[0],axis=1)

IndexError: ignored

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/original_epilepsy_types_new6.csv')
df =df.drop(['Unnamed: 0'],axis=1)
# df
zeros_count = [0,0,0,0,0,0,0]
for i in {0,1,2,3,4,5,6} :

# Assuming your DataFrame is named 'df' and the column you want to check is named 'column_name'
    zeros_count[i] = (df['Label'] == i).sum()
    # zeros_count[1] = (df['Label'] == 1).sum()
    # zeros_count[2] = (df['Label'] == 2).sum()
    # zeros_count[3] = (df['Label'] == 3).sum()
    # zeros_count[4]= (df['Label'] == 4).sum()
    # zeros_count[5] = (df['Label'] == 5).sum()
    # zeros_count[6] = (df['Label'] == 6).sum()


print("Number:", zeros_count)


Number: [4050, 4049, 4049, 4049, 4049, 4049, 4049]


In [ ]:
import numpy as np

random_numbers = np.random.randint(0, 9678, size=5629)
random_numbers

array([7114, 8824, 1575, ..., 1344, 4000, 7812])